openapi: 3.0.0
info:
  title: Sample App API
  version: 1.0.0
paths:
  /apps:
    get:
      summary: List Apps
      description: Retrieve a list of apps.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: []
    post:
      summary: Create an App
      description: Create a new app.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/App"
      responses:
        "201":
          description: App created successfully
          content:
            application/json:
              example: {}
  /apps/{appName}:
    get:
      summary: Get App by Name
      description: Retrieve an app by name.
      parameters:
        - name: appName
          in: path
          required: true
          schema:
            type: string
          example: my-first-prompt-app
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: {}
        "404":
          description: App not found
    put:
      summary: Update App
      description: Update an existing app by name.
      parameters:
        - name: appName
          in: path
          required: true
          schema:
            type: string
          example: my-first-prompt-app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/App"
      responses:
        "200":
          description: App updated successfully
        "404":
          description: App not found
    delete:
      summary: Delete App
      description: Delete an app by name.
      parameters:
        - name: appName
          in: path
          required: true
          schema:
            type: string
          example: my-first-prompt-app
      responses:
        "204":
          description: App deleted successfully
        "404":
          description: App not found
components:
  schemas:
    App:
      type: object
      properties:
        id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
          example: "2021-08-31T18:00:00.000Z"
        updated_at:
          type: string
          format: date-time
          example: "2021-08-31T18:00:00.000Z"
        name:
          type: string
          example: my-first-prompt-app
        description:
          type: string
          example: This is my first prompt app!
        messages:
          type: array
          items:
            type: object
            properties:
              role:
                type: string
                enum: [system, user]
                example: user
              content:
                type: string
                example: Hello, world!
        model:
          type: object
          properties:
            name:
              type: string
              enum: [llama2-chat, codellama-instruct]
              example: llama2-chat
            max_tokens:
              type: integer
              example: 75
            temperature:
              type: number
              example: 0.0
            repeat_penalty:
              type: number
              example: 1.1
            repeat_penalty_last_n_tokens:
              type: integer
              example: 64
            top_k:
              type: integer
              example: 0
            top_p:
              type: number
              example: 1.0
