spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "prompts"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "completions-api"
source = "target/wasm32-wasi/release/completions_api.wasm"
allowed_http_hosts = []
ai_models = ["llama2-chat", "codellama-instruct"]
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --release"
workdir = "api/completions"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
id = "apps-api"
source = "target/wasm32-wasi/release/apps_api.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/api/apps/..."
[component.build]
command = "cargo build --release"
workdir = "api/apps"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "web"
files = [ { source = "web/dist", destination = "/" } ]
environment = { FALLBACK_PATH = "index.html" }
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
workdir = "web"
